### ISSUE TITLE
What are the pros and cons of the Apache 2.0 license?

### ISSUE THREAD

**Issue by jdenen** [SmartColumbusOS/TechnicalWorkingGroup#10]
Given the open ended nature of #3, I want to accumulate a more concrete list of pros and cons for each of our [shortlisted](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Licensing-Models) license options.

Please fill out relevant sections in your comments.

# Apache 2.0

## References

* [summary](https://opensource.org/licenses/Apache-2.0)

## Pros

* _todo_

## Cons

* _todo_

## Other considerations

* _todo_

**Comment by skpy** [comment]
Pros:
* developed by the Apache Software Foundation
* used by most ASF projects, so well established
* permissive, and free software approved

**Comment by PhilNorman2** [comment]
Pros

- Permissive license which is preferred by TWG
- Compatible with LGPLv3, GPLv3 and Affero GPLv3
- Explicitly covers patent grant in embedded CLA

Cons

- More complex than MIT due to CLA
- Not as compatible with other open sources licenses as MIT

**Comment by PhilNorman2** [comment]
A couple of additional potential cons of Apache 2.0 vis a vis MIT.  I am not sure these are critical, but add to the overhead of things to remember to do and rules to follow.

- The Apache license requires that unmodified parts in derived works keep the Apache License.
- In every licensed file change, there must be a notification stating that changes have been made in the file, i.e., a modification notice must be made.

**Comment by bilsch** [comment]
> In every licensed file change, there must be a notification stating that changes have been made in the file, i.e., a modification notice must be made.

Would this be covered by a comment in github either on the PR or commit message?

**Comment by PhilNorman2** [comment]
The actual text in the license is "You must cause any modified files to carry prominent notices stating that You changed the file".  Seems like that means the modified file rather than the version control software but I am not sure.
