### ISSUE TITLE
What are the pros and cons of the MIT license?

### ISSUE THREAD

**Issue by jdenen** [SmartColumbusOS/TechnicalWorkingGroup#12]
Given the open ended nature of #3, I want to accumulate a more concrete list of pros and cons for each of our [shortlisted](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Licensing-Models) license options.

Please fill out relevant sections in your comments.

# MIT

## References

* [summary](https://opensource.org/licenses/MIT)

## Pros

* _todo_

## Cons

* _todo_

## Other considerations

* _todo_

**Comment by skpy** [comment]
Pros:
* most liberal license.
* used by Ruby, and very popular within that community.

**Comment by PhilNorman2** [comment]
Pros:

- simplest license
- most compatible for combining code in other open source libraries
- permissive license which is preferred by TWG
- most commonly used license (although Apache is gaining on it)

Cons: 
- does not explicitly cover patent grant (question for legal)
- would not cover trademark restrictions (if required)
