### ISSUE TITLE
Do we want a GitHub project?

### ISSUE THREAD

**Issue by jdenen** [SmartColumbusOS/TechnicalWorkingGroup#13]
I can setup a [GitHub project](https://help.github.com/articles/about-project-boards/) for this repository. Each new issue can fall into a backlog, moved to "in progress", etc. 

Given the talk of #3 being like an epic, it occurred to me that a board could be useful. Thoughts?

**Comment by jdenen** [comment]
It would also be beneficial as we have previously talked about using GitHub over Jira, and this could be a canary for that.

**Comment by bilsch** [comment]
I think this is a great idea @jdenen

**Comment by jdenen** [comment]
Done
