### ISSUE TITLE
Define Criteria for evaluating Licenses

### ISSUE THREAD

**Issue by PhilNorman2** [SmartColumbusOS/TechnicalWorkingGroup#15]

**Comment by PhilNorman2** [comment]
This issue is used to track the development of criteria for evaluating licenses.  The living artifact is the wiki page:

https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Open-Source-Licensing-Criteria

This issue will be closed when the artifact is approved.

**Comment by PhilNorman2** [comment]
Looking for input on https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Open-Source-Licensing-Criteria.  In particular, need to be sure we are OK with permissive licenses from a policy view, meaning we don't mind if derivative works end up being proprietary.  Also, need to know if we want to allow trademark grants, e.g., allowing someone to use the SmartColumbus logo to represent the work (as opposed to allowing 'powered by SmartColumbus' along with the logo).  Please provide input ASAP, so we can begin evaluating licenses according to the criteria to prepare for a possible meeting with an attorney the first week of January.

**Comment by monicamcjunkin** [comment]
Thank you for keeping this going, @PhilNorman2.
I have a related question for the group - Tammy is setting up a meeting in January with the city attorney and other IP experts. What questions would we have for them?  Or what are our thoughts that we'd like to run by legal minds?  We just need a brief statement that could get familiar with our work ahead of the meeting.

**Comment by PhilNorman2** [comment]
One question I would have is whether there are terms and conditions related to the City and other government agencies beyond the criteria we are evaluating.  The [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would be a good example to give them as it is a permissive license that embeds a CLA (Contributor License Agreement).   From that maybe they could tell us what is missing or inappropriate.  Another question is whether they are comfortable with crafting a CLA?

**Comment by PhilNorman2** [comment]
Also, maybe the city attorney may have some insight on the trademark grant question.

**Comment by monicamcjunkin** [comment]
Perfect, thanks

**Comment by PhilNorman2** [comment]
I added a wiki page for [Criteria Based License Evaluation](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Criteria-Based-License-Evaluation).  

I uploaded the image to the github repository and committed it to the master and linked to it from the wiki page.  @bilsch if that is not the best way, let me know.  Also, I found opening the image in a new tab made it more readable.

Based on our preference for permissive licenses I think we can probably rule out GPLv3 and LGPLv3 (at least for application source), leaving us with Apache 2.0 and MIT (X11).  It is difficult to make a recommendation or even complete pros and cons without knowing the terms and conditions required and the ensuing legal costs.  Here are some additional questions for the legal and IP experts that may shed more light.

1. Does MIT's lack of restrictions implicitly cover a patent grant?  See [article](https://opensource.com/article/18/3/patent-grant-mit-license)
2. If a CLA is required, is the legal team comfortable with ensuring the CLA is compatible with GPL?  Note that this would not be an issue with Apache 2.0 as it already has an embedded CLA and it is compatible with GPLv3.  I believe accomplishing that was quite a bit of legal work.

If Apache 2.0's terms and conditions are sufficient that would mean lower costs in terms of legal work because we would conceivably not need a CLA.    The same thing might be true for MIT if the answer to the first question is 'yes' and we do not require a trademark restriction or any other additional terms and conditions.   But all this is just postulating.

**Comment by bilsch** [comment]
Sorry for not responding earlier @PhilNorman2 - yea what you have done on this is fantastic!

**Comment by PhilNorman2** [comment]
I have updated the [Criteria Based License Evaluation](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Criteria-Based-License-Evaluation) to include sections for Purpose, Analysis including Pros and Cons, and Recommendations.  The recommendations section doesn't come to a clear conclusion due to issues over lack of explicit patent grant with the MIT license and uncertainty about trademark grant that needs to be clarified before fully endorsing Apache 2.0 as a viable candidate.  IMHO I would be a little surprised if we chose to provide a trademark grant and due to the fact that the MIT patent grant is not explicit I would tend to think Apache 2.0 is a viable candidate.  Other factors could outweigh these considerations, so after today's meeting with the legal team I would like to get wider input on this from the group.

**Comment by PhilNorman2** [comment]
Updated the draft [Criteria Based License Evaluation ](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Criteria-Based-License-Evaluation) with more fleshed out recommendation.  Basically the primary recommendation is Apache 2.0 with MIT being the secondary.   Also has a list of questions that need to be answered.  Tried to separate this from the legal questions but there is some overlap.

**Comment by PhilNorman2** [comment]
@monicamcjunkin and @tchellis ,  @bilsch  provided me with a video recording of the  link to the legal questions from Wednesday.  I updated the [legal questions wiki page](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Questions-for-Legal-Team) to include the answers after listening to the recording.
