### ISSUE TITLE
Ensure proper permissions for all members

### ISSUE THREAD

**Issue by bilsch** [SmartColumbusOS/TechnicalWorkingGroup#16]
We have had a number of questions come up regarding permissions with issues. Some members ( at least Phil Norman have been unable to edit labels etc.

All twg members should be able to edit labels, assign / edit milestones etc.

I am unsure what the permissions or membership issues may be. As part of this issue I would like to adjust the documentation in the wiki [Group working model](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Group-working-model) to list the steps / states necessary. An optional choice here would be to have a document specific to the on-boarding process for twg members.

As I have worked most with @rubberduck203 on this issue I am assigning it to him to start.

**Comment by rubberduck203** [comment]
@bilsch I need github usernames of the folks you want added. It’s just a matter of @jdenen or I adding them to the repository as a Github “contributor”.

**Comment by bilsch** [comment]
I don't have access to edit the members. We have a few people responding to update the [Roster](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Roster) can these be synced up @rubberduck203 ?

**Comment by rubberduck203** [comment]
I understand you don’t have that access @bilsch. 
I need a list of github usernames you’d like to have added. 
I’m happy to do so, but I can’t without that information.

**Comment by PhilNorman2** [comment]
I have permission now to do what I need to do, assign and create labels.  Thanks @bilsch and @rubberduck203!

**Comment by rubberduck203** [comment]
Excellent!
