### ISSUE TITLE
Feedback Request: Pull Request Model

### ISSUE THREAD

**Issue by rubberduck203** [SmartColumbusOS/TechnicalWorkingGroup#7]
Looking towards deliverable 3 ("Identify a process for code commit, core team membership, release pipeline"), I created a wiki page and process diagram describing the pull request model.
I'm sure this document will come as no surprise to any of the developers in the group, but we need to be sure to clearly communicate what this process looks like to our stakeholders.

Can someone give this a once over and let me know if I left anything out or something is confusing?
https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Pull-Request-Model

It actually would be great if one of our non-developer members could review it.

**Comment by ManApart** [comment]
I thought it was really clear, personally. I wonder if non technical people will know how to make the flow chart image big enough to read (open in new tab etc). Might be worth have a line of instructions, but maybe it's fine.

**Comment by joelgerber** [comment]
I think this is great. I'm not so worried about chart size. I suspect that most non-tech folks would just send the link to their tech resource.

**Comment by rubberduck203** [comment]
Before I close this, should I add (or create a second diagram) with an optional CLA workflow? Thoughts?

**Comment by ManApart** [comment]
I'd like to see it added if it doesn't add too much complexity to the chart.

**Comment by rubberduck203** [comment]
I’ll mock up a second diagram & add it to the wiki. Folks can decide later on whether or not we should include it in the final.

**Comment by bilsch** [comment]
I would also like to see a discussion around the workflow being captured as a Contributions.md style [doc](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) ( eg in text form and as a part of our repositories )

**Comment by rubberduck203** [comment]
Is that really necessary? I assume most developers are familiar with how pull requests work. This is for the benefit of the non-devs who will be receiving our recommendations. 

If we want to discuss that, let’s move it to #4.
