### ISSUE TITLE
What are the pros and cons of the GPLv3 license?

### ISSUE THREAD

**Issue by jdenen** [SmartColumbusOS/TechnicalWorkingGroup#9]
Given the open ended nature of #3, I want to accumulate a more concrete list of pros and cons for each of our [shortlisted](https://github.com/SmartColumbusOS/TechnicalWorkingGroup/wiki/Licensing-Models) license options.

Please fill out relevant sections in your comments.

# GPLv3

## References

* [summary](https://www.gnu.org/licenses/gpl-3.0.en.html)

## Pros

* _todo_

## Cons

* _todo_

## Other considerations

* _todo_

**Comment by bilsch** [comment]
Great idea @jdenen

**Comment by PhilNorman2** [comment]
Cons

- Not permissive.  Distribution, Modification, and sub-licensing of released code is copylefted. 
- Only compatible with Afferro GPLv3.

**Comment by PhilNorman2** [comment]
One more con.  Adoption is trending down,.
